services:
  db:
    image: postgres:16
    container_name: db
    env_file: ./.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    mem_limit: 512m

volumes:
  postgres-data:
